#!/bin/bash

# INSTALL ARP-SCAN
locate_ARPSCAN=$(which arp-scan)
[ ! -f "$locate_ARPSCAN" ] && sudo apt install arp-scan
[ $? -ne 0 ] && exit 1

# INSTALL AIRCRACK-NG
locate_AIRCRACKNG=$(which aircrack-ng)
[ ! -f "$locate_AIRCRACKNG" ] && sudo apt install aircrack-ng
[ $? -ne 0 ] && exit 1

# CREATING ESSENTIAL DIRECTORIES
[ ! -d _gateway ] && mkdir _gateway
[ ! -d result ] && mkdir result
[ ! -d white_list ] && mkdir white_list