#!/bin/bash

# INSTALL ARP-SCAN
LOCATE_ARPSCAN=$(which arp-scan)
[ ! -f "$LOCATE_ARPSCAN" ] && sudo apt install arp-scan
[ $? -ne 0 ] && exit 1

# INSTALL AIRCRACK-NG
LOCATE_AIRCRACKNG=$(which aircrack-ng)
[ ! -f "$LOCATE_AIRCRACKNG" ] && sudo apt install aircrack-ng
[ $? -ne 0 ] && exit 1

# INSTALL FIGLET
LOCATE_FIGLET=$(which figlet)
[ ! -f "$LOCATE_FIGLET" ] && sudo apt install figlet
[ $? -ne 0 ] && exit 1

# CREATING ESSENTIAL DIR
[ ! -d _gateway ] && mkdir _gateway
[ ! -d result ] && mkdir result
[ ! -d store ] && mkdir store
[ ! -d store/white_list ] && mkdir store/white_list
[ ! -d store/black_list ] && mkdir store/black_list

