#!/bin/bash

CHECKROOT () {
    echo -e "\e[1m\e[46m\e[37m\e[5m PLEASE RUN THIS SCRIPT AS ROOT \e[0m" | sed  -e :a -e "s/^.\{1,$(tput cols)\}$/ & /;ta" | tr -d '\n' | head -c $(tput cols)
    exit 1
}

[ "$EUID" -ne 0 ] && CHECKROOT

./install

get_router_credentials () {
    router_ip=$(netstat -nr | awk '$1 == "0.0.0.0"{print$2}')
    router_mac=$(ip neigh|grep "$(ip -4 route list 0/0|head -1|cut -d ' ' -f3) "|cut -d' ' -f5|tr '[a-f]' '[A-F]')
    interface=$(ip route get 8.8.8.8 | grep -oP 'dev \K[^ ]+')
    bssid=$(iwconfig "$interface" | sed -n 's/.*Access Point: \([0-9\:A-F]\{17\}\).*/\1/p')
    channel=$(iw "$interface" info | grep "channel"| awk '{print $2}')
    if [ "$router_ip" != "" ] || [ "$router_mac" != "" ] || [ "$ssid" != "" ] 
    then
    touch store/white_list/list.txt && touch RES/arp-scan.txt && touch store/black_list/file.txt
    echo "$router_ip" > ROUTER/IP.txt && echo "$router_mac" > ROUTER/MAC.txt && echo "$interface" > ROUTER/IF.txt && echo "$bssid" > ROUTER/BSSID.txt && echo "$channel" > ROUTER/CH.txt
    else
    echo -e "\e[1m\e[46m\e[37m\e[5m PLEASE CONNECT TO A ROUTER \e[0m" | sed  -e :a -e "s/^.\{1,$(tput cols)\}$/ & /;ta" | tr -d '\n' | head -c $(tput cols)
    exit
    fi 
}
get_router_credentials

clear
echo ""
LOGOTXT="AP -- MAG"
FONTPATH="FONT/Bloody.flf"
LOGO=$(figlet -w $(tput cols) -f "$FONTPATH" -c "$LOGOTXT")
echo -e "\e[1m\e[32m$LOGO\e[0m"
python3 run.py